//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingResults
    {
        public int TestId { get; set; }
        public System.DateTime TestDate { get; set; }
        public string CardNumber { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public int TestDurationMinutes { get; set; }
        public int TotalQuestions { get; set; }
        public int CorrectAnswersCount { get; set; }
        public string Grade { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
