//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAnswers
    {
        public int AnswerId { get; set; }
        public int TestId { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
